# Site settings
title: Travel Blog
email: marklehmann26@gmail.com
description: Fun Blog about traveling.
baseurl: "/travel-blog"
twitter_username: marklehmann26
avatar: "https://pbs.twimg.com/profile_images/553352464444194816/Q0GFLymF.jpeg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Mark Lehmann" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
